apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingi
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: "ramya"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

